/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    AResult: typeof import('ant-design-vue/es')['Result']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATableColumn: typeof import('ant-design-vue/es')['TableColumn']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    BasicButton: typeof import('./../src/components/Button/src/BasicButton.vue')['default']
    BasicForm: typeof import('./../src/components/Form/BasicForm.vue')['default']
    BasicModal: typeof import('./../src/components/Modal/src/BasicModal.vue')['default']
    BasicTable: typeof import('./../src/components/VxeTable/BasicTable.vue')['default']
    FetchTable: typeof import('./../src/components/VxeTable/FetchTable.vue')['default']
    HoverContainer: typeof import('./../src/components/Application/HoverContainer.vue')['default']
    IconAntDesignFullscreenExitOutlined: typeof import('~icons/ant-design/fullscreen-exit-outlined')['default']
    IconAntDesignFullscreenOutlined: typeof import('~icons/ant-design/fullscreen-outlined')['default']
    IconAntDesignLeftCircleOutlined: typeof import('~icons/ant-design/left-circle-outlined')['default']
    IconAntDesignLeftOutlined: typeof import('~icons/ant-design/left-outlined')['default']
    IconAntDesignRedoOutlined: typeof import('~icons/ant-design/redo-outlined')['default']
    IconAntDesignRightOutlined: typeof import('~icons/ant-design/right-outlined')['default']
    IconCustomLogo: typeof import('~icons/custom/logo')['default']
    LayoutMenu: typeof import('./../src/components/Menus/LayoutMenu.vue')['default']
    Loading: typeof import('./../src/components/Loading/Loading.vue')['default']
    ModalClose: typeof import('./../src/components/Modal/src/components/ModalClose.vue')['default']
    RouteMenu: typeof import('./../src/components/Menus/RouteMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemLogo: typeof import('./../src/components/Application/SystemLogo.vue')['default']
  }
}
